### PR TITLE
fix GitHub authentication

### LINKED ISSUE #154: Signing in with github does not seem to be working, any missing configurations?

### PR DESCRIPTION
**Pull request by sophiedeziel**
Fixes #154

### CODE REVIEW

**Comment by sophiedeziel** [comment]
@benichu That will fix your login issue. Want to review?

File: app/models/user.rb [hunk 1]
```diff
@@ -27,29 +27,51 @@ class User < ActiveRecord::Base
...
+    end
 
-  def self.default_user
-    User.find_by(email: DEFAULT_USER_EMAIL)
-  end
+    def default_user
+      User.find_by(email: DEFAULT_USER_EMAIL)
+    end
+
+    private
```
Comment (steakunderscore) [inline app/models/user.rb]: Can't have private class methods..?

Comment (sophiedeziel) [inline app/models/user.rb]: They actually are private class methods because they are inside of `class << self`
